"""Train the baseline or an ECAFA-YOLO model using a local dataset YAML."""

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
DEFAULT_MODEL = ROOT / "ultralytics/cfg/models/11/yolo11-CAFA.yaml"


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data", type=Path, required=True, help="Dataset YAML generated by a preparation script")
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL, help="Local model YAML or checkpoint")
    parser.add_argument("--scale", choices=("n", "s", "m", "l", "x"), help="YAML model size; defaults to n for unscaled filenames")
    parser.add_argument("--epochs", type=int, default=200)
    parser.add_argument("--imgsz", type=int, default=640)
    parser.add_argument("--batch", type=int, default=64)
    parser.add_argument("--device", default="cuda", help="cuda, GPU index, comma-separated GPU indices, or cpu")
    parser.add_argument("--workers", type=int, default=16)
    parser.add_argument("--cache", choices=("ram", "disk", "false"), default="ram", help="Dataset cache mode")
    parser.add_argument("--close-mosaic", type=int, default=9999)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--deterministic", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--cpu-threads", type=int, default=8)
    parser.add_argument("--resume", action="store_true", help="Resume from a .pt checkpoint passed to --model")
    parser.add_argument("--single-cls", action="store_true", help="Treat all dataset classes as one class")
    parser.add_argument("--optimizer", default="SGD")
    parser.add_argument("--lr0", type=float, default=0.01)
    parser.add_argument("--project", default="runs/train")
    parser.add_argument("--name", default="exp")
    parser.add_argument("--no-amp", action="store_true", help="Disable automatic mixed precision")
    return parser.parse_args()


def set_seed(seed=42, deterministic=True, cpu_threads=8):
    """Match the initialization in the original GTSDB and TT100K training scripts."""
    import random

    import numpy as np
    import torch

    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.enabled = True
    torch.backends.cudnn.deterministic = deterministic
    torch.backends.cudnn.benchmark = not deterministic
    torch.use_deterministic_algorithms(deterministic)
    torch.set_num_threads(cpu_threads)


def main():
    args = parse_args()
    for path in (args.data, args.model):
        if not path.is_file():
            raise FileNotFoundError(path)
    model_path = args.model.resolve()
    if args.resume and model_path.suffix.lower() != ".pt":
        raise ValueError("--resume requires a .pt checkpoint passed to --model")
    if model_path.suffix.lower() in {".yaml", ".yml"}:
        # The local Ultralytics loader resolves yolo11x-*.yaml to yolo11-*.yaml
        # and reads the x entry in its scales table. No duplicate YAML is needed.
        scale = args.scale
        if scale is None and not re.match(r"yolo11[nslmx]", model_path.stem):
            scale = "n"
        if scale is not None:
            if not re.match(r"yolo11(?:[nslmx])?(?:-|$)", model_path.stem):
                raise ValueError("--scale expects a yolo11[-...].yaml model filename")
            name = re.sub(r"^yolo11[nslmx]?", "yolo11" + scale, model_path.name)
            model_path = model_path.with_name(name)
    elif args.scale is not None:
        raise ValueError("--scale applies to YAML models, not trained checkpoints")

    from ultralytics import YOLO
    from ultralytics.utils.torch_utils import model_info

    set_seed(args.seed, args.deterministic, args.cpu_threads)
    model = YOLO(str(model_path), task="detect")
    model_info(model.model, verbose=True, imgsz=args.imgsz)
    model.train(
        data=str(args.data.resolve()), task="detect", epochs=args.epochs, imgsz=args.imgsz,
        batch=args.batch, device=args.device, workers=args.workers,
        optimizer=args.optimizer, lr0=args.lr0, lrf=0.01, cos_lr=False,
        mosaic=0.0, mixup=0.0, copy_paste=0.0, close_mosaic=args.close_mosaic,
        cache=False if args.cache == "false" else args.cache,
        resume=args.resume, single_cls=args.single_cls,
        seed=args.seed, deterministic=args.deterministic,
        amp=not args.no_amp, project=args.project, name=args.name,
    )


if __name__ == "__main__":
    main()
